### ISSUE TITLE
Fata error:

### ISSUE THREAD

**Issue by alexlii1971** [stephencaosemene/woocommerce-global-cart#2]
when It is activated both by network or only in a sub site, errors will be show:

Warning: require(/var/www/mysite.com/htdocs/wp-content/plugins/woocommerce-global-cart-master/includes/class-woocommerce-global-cart.php): failed to open stream: No such file or directory in /var/www/mysite.com/htdocs/wp-content/plugins/woocommerce-global-cart-master/woocommerce-global-cart.php on line 58

**Comment by stephenafamo** [comment]
Sorry, this plugin does not work at this time. 

It was created because I hope to build it out but I have not had the time to do so yet.
